;;;; Parent-pointer session. Node is a fixed list:
;;;; (id parent kind text x y). Parent 0 means none.

(defun ham-node (id parent kind text x y)
  (list id parent kind text x y))

(defun ham-id (n) (nth 0 n))
(defun ham-parent (n) (nth 1 n))
(defun ham-kind (n) (nth 2 n))
(defun ham-text (n) (nth 3 n))
(defun ham-xy (n) (list (nth 4 n) (nth 5 n)))

(defun ham-empty ()
  (list :title "" :seq 0 :nodes nil))

(defun ham-title (s) (getf s :title))
(defun ham-nodes (s) (getf s :nodes))

(defun ham-find (s id)
  (let ((hit nil))
    (dolist (n (ham-nodes s))
      (when (= (ham-id n) id)
        (setq hit n)))
    hit))

(defun ham-depth (s id)
  (let ((d 0)
        (cur id)
        (guard 0))
    (tagbody
     again
      (when (or (= cur 0) (> guard 64))
        (return-from ham-depth d))
      (setq guard (+ guard 1))
      (let ((n (ham-find s cur)))
        (when (null n)
          (return-from ham-depth d))
        (setq cur (ham-parent n))
        (setq d (+ d 1)))
      (go again))))

(defun ham-root (s title)
  (let ((n (ham-node 1 0 'identity title 0.0d0 0.0d0)))
    (list :title title :seq 1 :nodes (list n))))

(defun ham-add (s parent kind text)
  (let* ((p (ham-find s parent))
         (sib 0)
         (depth 0)
         (xy nil)
         (id 0)
         (node nil))
    (when (null p)
      (error "missing parent"))
    (dolist (n (ham-nodes s))
      (when (= (ham-parent n) parent)
        (setq sib (+ sib 1))))
    (setq depth (+ (ham-depth s parent) 1))
    (setq xy (ham-place (ham-xy p) sib depth))
    (when (<= (ham-norm xy) (ham-norm (ham-xy p)))
      (error "child not farther out"))
    (setq id (+ (getf s :seq) 1))
    (setq node (ham-node id parent kind text (car xy) (cadr xy)))
    (list :title (ham-title s)
          :seq id
          :nodes (append (ham-nodes s) (list node)))))

(defun ham-save (s path)
  (with-open-file (out path :direction :output :if-exists :supersede :if-does-not-exist :create)
    (prin1 (list 'session (ham-title s) (cons 'nodes (ham-nodes s))) out)
    (terpri out))
  s)

(defun ham-load (path)
  (with-open-file (in path :direction :input)
    (let ((form (read in)))
      (list :title (nth 1 form)
            :seq (reduce #'max (mapcar #'ham-id (cdr (nth 2 form))))
            :nodes (cdr (nth 2 form))))))

(defun ham-brief (s)
  (let ((goals nil) (files nil) (decisions nil) (failures nil))
    (dolist (n (ham-nodes s))
      (cond ((eq (ham-kind n) 'goal) (push (ham-text n) goals))
            ((eq (ham-kind n) 'file) (push (ham-text n) files))
            ((eq (ham-kind n) 'decision) (push (ham-text n) decisions))
            ((eq (ham-kind n) 'failure) (push (ham-text n) failures))))
    (with-output-to-string (out)
      (format out "~a~%" (ham-title s))
      (when goals (format out "Goals: ~{~a~^; ~}~%" (nreverse goals)))
      (when files (format out "Files: ~{~a~^; ~}~%" (nreverse files)))
      (when decisions (format out "Decisions: ~{~a~^; ~}~%" (nreverse decisions)))
      (when failures (format out "Failures: ~{~a~^; ~}~%" (nreverse failures))))))
